[package]
name = "json-prettier"
version = "0.3.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "json_prettier"
crate-type = ["dylib"]

[dependencies]
serde_json = "1.0.149"

[dev-dependencies]
libloading = "0.7.4"
